# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Python37-32\qtcursortex with dict 2020 1 9\newStart.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1358, 755)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1351, 721))
        self.tabWidget.setObjectName("tabWidget")
        self.main = QtWidgets.QWidget()
        self.main.setObjectName("main")
        self.inputText = QtWidgets.QTextEdit(self.main)
        self.inputText.setGeometry(QtCore.QRect(40, 30, 561, 281))
        self.inputText.setObjectName("inputText")
        self.fireLine = QtWidgets.QLineEdit(self.main)
        self.fireLine.setGeometry(QtCore.QRect(40, 340, 201, 31))
        self.fireLine.setObjectName("fireLine")
        self.fireButton = QtWidgets.QPushButton(self.main)
        self.fireButton.setGeometry(QtCore.QRect(260, 340, 101, 23))
        self.fireButton.setObjectName("fireButton")
        self.highlightButton = QtWidgets.QPushButton(self.main)
        self.highlightButton.setGeometry(QtCore.QRect(270, 500, 75, 23))
        self.highlightButton.setObjectName("highlightButton")
        self.underlineButton = QtWidgets.QPushButton(self.main)
        self.underlineButton.setGeometry(QtCore.QRect(270, 460, 75, 23))
        self.underlineButton.setObjectName("underlineButton")
        self.italicButton = QtWidgets.QPushButton(self.main)
        self.italicButton.setGeometry(QtCore.QRect(270, 420, 75, 23))
        self.italicButton.setObjectName("italicButton")
        self.boldButton = QtWidgets.QPushButton(self.main)
        self.boldButton.setGeometry(QtCore.QRect(270, 380, 75, 23))
        self.boldButton.setObjectName("boldButton")
        self.openFileButton = QtWidgets.QPushButton(self.main)
        self.openFileButton.setGeometry(QtCore.QRect(420, 520, 75, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.tabWidget.addTab(self.main, "")
        self.token = QtWidgets.QWidget()
        self.token.setObjectName("token")
        self.givenText = QtWidgets.QTextEdit(self.token)
        self.givenText.setGeometry(QtCore.QRect(230, 20, 591, 71))
        self.givenText.setObjectName("givenText")
        self.firstText = QtWidgets.QTextEdit(self.token)
        self.firstText.setGeometry(QtCore.QRect(230, 130, 591, 81))
        self.firstText.setObjectName("firstText")
        self.secondText = QtWidgets.QTextEdit(self.token)
        self.secondText.setGeometry(QtCore.QRect(230, 250, 591, 81))
        self.secondText.setObjectName("secondText")
        self.thirdText = QtWidgets.QTextEdit(self.token)
        self.thirdText.setGeometry(QtCore.QRect(230, 390, 591, 81))
        self.thirdText.setObjectName("thirdText")
        self.sentTokenizeButton = QtWidgets.QPushButton(self.token)
        self.sentTokenizeButton.setGeometry(QtCore.QRect(10, 20, 91, 23))
        self.sentTokenizeButton.setObjectName("sentTokenizeButton")
        self.totalSentLabel = QtWidgets.QLabel(self.token)
        self.totalSentLabel.setGeometry(QtCore.QRect(20, 60, 81, 41))
        self.totalSentLabel.setObjectName("totalSentLabel")
        self.givenDownButton = QtWidgets.QPushButton(self.token)
        self.givenDownButton.setGeometry(QtCore.QRect(130, 60, 75, 23))
        self.givenDownButton.setObjectName("givenDownButton")
        self.givenLabel = QtWidgets.QLabel(self.token)
        self.givenLabel.setGeometry(QtCore.QRect(850, 50, 56, 12))
        self.givenLabel.setObjectName("givenLabel")
        self.firstLabel = QtWidgets.QLabel(self.token)
        self.firstLabel.setGeometry(QtCore.QRect(850, 160, 56, 12))
        self.firstLabel.setObjectName("firstLabel")
        self.secondLabel = QtWidgets.QLabel(self.token)
        self.secondLabel.setGeometry(QtCore.QRect(840, 280, 56, 20))
        self.secondLabel.setObjectName("secondLabel")
        self.thirdLabel = QtWidgets.QLabel(self.token)
        self.thirdLabel.setGeometry(QtCore.QRect(850, 420, 56, 12))
        self.thirdLabel.setObjectName("thirdLabel")
        self.firstUpButton = QtWidgets.QPushButton(self.token)
        self.firstUpButton.setGeometry(QtCore.QRect(130, 130, 75, 23))
        self.firstUpButton.setObjectName("firstUpButton")
        self.secondUpButton = QtWidgets.QPushButton(self.token)
        self.secondUpButton.setGeometry(QtCore.QRect(130, 250, 75, 23))
        self.secondUpButton.setObjectName("secondUpButton")
        self.thirdUpButton = QtWidgets.QPushButton(self.token)
        self.thirdUpButton.setGeometry(QtCore.QRect(130, 390, 75, 23))
        self.thirdUpButton.setObjectName("thirdUpButton")
        self.firstDownButton = QtWidgets.QPushButton(self.token)
        self.firstDownButton.setGeometry(QtCore.QRect(130, 160, 75, 23))
        self.firstDownButton.setObjectName("firstDownButton")
        self.secondDownButton = QtWidgets.QPushButton(self.token)
        self.secondDownButton.setGeometry(QtCore.QRect(130, 280, 75, 23))
        self.secondDownButton.setObjectName("secondDownButton")
        self.tokenRadioBox = QtWidgets.QGroupBox(self.token)
        self.tokenRadioBox.setGeometry(QtCore.QRect(220, 510, 351, 41))
        self.tokenRadioBox.setFlat(True)
        self.tokenRadioBox.setObjectName("tokenRadioBox")
        self.optionTypeABCButtonOne = QtWidgets.QRadioButton(self.tokenRadioBox)
        self.optionTypeABCButtonOne.setGeometry(QtCore.QRect(20, 20, 90, 16))
        self.optionTypeABCButtonOne.setObjectName("optionTypeABCButtonOne")
        self.optionTypeABCButtonTwo = QtWidgets.QRadioButton(self.tokenRadioBox)
        self.optionTypeABCButtonTwo.setGeometry(QtCore.QRect(90, 20, 90, 16))
        self.optionTypeABCButtonTwo.setObjectName("optionTypeABCButtonTwo")
        self.optionTypeABCButtonThree = QtWidgets.QRadioButton(self.tokenRadioBox)
        self.optionTypeABCButtonThree.setGeometry(QtCore.QRect(150, 20, 90, 16))
        self.optionTypeABCButtonThree.setObjectName("optionTypeABCButtonThree")
        self.optionTypeABCButtonFour = QtWidgets.QRadioButton(self.tokenRadioBox)
        self.optionTypeABCButtonFour.setGeometry(QtCore.QRect(220, 20, 90, 16))
        self.optionTypeABCButtonFour.setObjectName("optionTypeABCButtonFour")
        self.optionTypeABCButtonFive = QtWidgets.QRadioButton(self.tokenRadioBox)
        self.optionTypeABCButtonFive.setGeometry(QtCore.QRect(280, 20, 90, 16))
        self.optionTypeABCButtonFive.setObjectName("optionTypeABCButtonFive")
        self.optionTypeABCRandomButton = QtWidgets.QPushButton(self.token)
        self.optionTypeABCRandomButton.setGeometry(QtCore.QRect(600, 520, 75, 23))
        self.optionTypeABCRandomButton.setObjectName("optionTypeABCRandomButton")
        self.givenCopyButton = QtWidgets.QPushButton(self.token)
        self.givenCopyButton.setGeometry(QtCore.QRect(910, 40, 75, 23))
        self.givenCopyButton.setObjectName("givenCopyButton")
        self.firstCopyButton = QtWidgets.QPushButton(self.token)
        self.firstCopyButton.setGeometry(QtCore.QRect(910, 150, 75, 23))
        self.firstCopyButton.setObjectName("firstCopyButton")
        self.secondCopyButton = QtWidgets.QPushButton(self.token)
        self.secondCopyButton.setGeometry(QtCore.QRect(910, 280, 75, 23))
        self.secondCopyButton.setObjectName("secondCopyButton")
        self.thirdCopyButton = QtWidgets.QPushButton(self.token)
        self.thirdCopyButton.setGeometry(QtCore.QRect(910, 410, 75, 23))
        self.thirdCopyButton.setObjectName("thirdCopyButton")
        self.tokenChoiceCopyButton = QtWidgets.QPushButton(self.token)
        self.tokenChoiceCopyButton.setGeometry(QtCore.QRect(890, 520, 101, 23))
        self.tokenChoiceCopyButton.setObjectName("tokenChoiceCopyButton")
        self.ABCCopyButton = QtWidgets.QPushButton(self.token)
        self.ABCCopyButton.setGeometry(QtCore.QRect(1020, 40, 75, 23))
        self.ABCCopyButton.setObjectName("ABCCopyButton")
        self.tabWidget.addTab(self.token, "")
        self.insertion = QtWidgets.QWidget()
        self.insertion.setObjectName("insertion")
        self.insertionAllocateButton = QtWidgets.QPushButton(self.insertion)
        self.insertionAllocateButton.setGeometry(QtCore.QRect(20, 30, 75, 23))
        self.insertionAllocateButton.setObjectName("insertionAllocateButton")
        self.insertionFullText = QtWidgets.QTextEdit(self.insertion)
        self.insertionFullText.setGeometry(QtCore.QRect(280, 160, 481, 371))
        self.insertionFullText.setObjectName("insertionFullText")
        self.insertionGivenCopyButton = QtWidgets.QPushButton(self.insertion)
        self.insertionGivenCopyButton.setGeometry(QtCore.QRect(940, 50, 75, 23))
        self.insertionGivenCopyButton.setObjectName("insertionGivenCopyButton")
        self.insertionTextCopyButton = QtWidgets.QPushButton(self.insertion)
        self.insertionTextCopyButton.setGeometry(QtCore.QRect(940, 190, 75, 23))
        self.insertionTextCopyButton.setObjectName("insertionTextCopyButton")
        self.insertionGivenLabel = QtWidgets.QLabel(self.insertion)
        self.insertionGivenLabel.setGeometry(QtCore.QRect(800, 60, 56, 12))
        self.insertionGivenLabel.setObjectName("insertionGivenLabel")
        self.insertionFullTextLabel = QtWidgets.QLabel(self.insertion)
        self.insertionFullTextLabel.setGeometry(QtCore.QRect(800, 190, 56, 12))
        self.insertionFullTextLabel.setObjectName("insertionFullTextLabel")
        self.groupBox = QtWidgets.QGroupBox(self.insertion)
        self.groupBox.setGeometry(QtCore.QRect(20, 220, 111, 191))
        self.groupBox.setObjectName("groupBox")
        self.insertionOne = QtWidgets.QRadioButton(self.groupBox)
        self.insertionOne.setGeometry(QtCore.QRect(10, 30, 90, 16))
        self.insertionOne.setObjectName("insertionOne")
        self.insertionTwo = QtWidgets.QRadioButton(self.groupBox)
        self.insertionTwo.setGeometry(QtCore.QRect(10, 60, 90, 16))
        self.insertionTwo.setObjectName("insertionTwo")
        self.insertionThree = QtWidgets.QRadioButton(self.groupBox)
        self.insertionThree.setGeometry(QtCore.QRect(10, 90, 90, 16))
        self.insertionThree.setObjectName("insertionThree")
        self.insertionFour = QtWidgets.QRadioButton(self.groupBox)
        self.insertionFour.setGeometry(QtCore.QRect(10, 120, 90, 16))
        self.insertionFour.setObjectName("insertionFour")
        self.insertionFive = QtWidgets.QRadioButton(self.groupBox)
        self.insertionFive.setGeometry(QtCore.QRect(10, 150, 90, 16))
        self.insertionFive.setObjectName("insertionFive")
        self.insertionAllocateLabel = QtWidgets.QLabel(self.insertion)
        self.insertionAllocateLabel.setGeometry(QtCore.QRect(20, 80, 191, 51))
        self.insertionAllocateLabel.setObjectName("insertionAllocateLabel")
        self.insertionGivenText = QtWidgets.QTextEdit(self.insertion)
        self.insertionGivenText.setGeometry(QtCore.QRect(280, 40, 471, 61))
        self.insertionGivenText.setObjectName("insertionGivenText")
        self.tabWidget.addTab(self.insertion, "")
        self.irrelevant = QtWidgets.QWidget()
        self.irrelevant.setObjectName("irrelevant")
        self.irreFullText = QtWidgets.QTextEdit(self.irrelevant)
        self.irreFullText.setGeometry(QtCore.QRect(270, 170, 481, 371))
        self.irreFullText.setObjectName("irreFullText")
        self.irreGivenText = QtWidgets.QTextEdit(self.irrelevant)
        self.irreGivenText.setGeometry(QtCore.QRect(270, 60, 471, 61))
        self.irreGivenText.setObjectName("irreGivenText")
        self.irreAllocateButton = QtWidgets.QPushButton(self.irrelevant)
        self.irreAllocateButton.setGeometry(QtCore.QRect(50, 50, 75, 23))
        self.irreAllocateButton.setObjectName("irreAllocateButton")
        self.irreAllocateLabel = QtWidgets.QLabel(self.irrelevant)
        self.irreAllocateLabel.setGeometry(QtCore.QRect(30, 100, 191, 51))
        self.irreAllocateLabel.setObjectName("irreAllocateLabel")
        self.irreTextCopyButton = QtWidgets.QPushButton(self.irrelevant)
        self.irreTextCopyButton.setGeometry(QtCore.QRect(940, 210, 75, 23))
        self.irreTextCopyButton.setObjectName("irreTextCopyButton")
        self.irreGivenLabel = QtWidgets.QLabel(self.irrelevant)
        self.irreGivenLabel.setGeometry(QtCore.QRect(780, 90, 101, 16))
        self.irreGivenLabel.setObjectName("irreGivenLabel")
        self.irreFullTextLabel = QtWidgets.QLabel(self.irrelevant)
        self.irreFullTextLabel.setGeometry(QtCore.QRect(790, 220, 56, 12))
        self.irreFullTextLabel.setObjectName("irreFullTextLabel")
        self.irreGivenCopyButton = QtWidgets.QPushButton(self.irrelevant)
        self.irreGivenCopyButton.setGeometry(QtCore.QRect(930, 80, 75, 23))
        self.irreGivenCopyButton.setObjectName("irreGivenCopyButton")
        self.irreGroupBox = QtWidgets.QGroupBox(self.irrelevant)
        self.irreGroupBox.setGeometry(QtCore.QRect(40, 260, 111, 191))
        self.irreGroupBox.setObjectName("irreGroupBox")
        self.irreOne = QtWidgets.QRadioButton(self.irreGroupBox)
        self.irreOne.setGeometry(QtCore.QRect(10, 30, 90, 16))
        self.irreOne.setObjectName("irreOne")
        self.irreTwo = QtWidgets.QRadioButton(self.irreGroupBox)
        self.irreTwo.setGeometry(QtCore.QRect(10, 60, 90, 16))
        self.irreTwo.setObjectName("irreTwo")
        self.irreThree = QtWidgets.QRadioButton(self.irreGroupBox)
        self.irreThree.setGeometry(QtCore.QRect(10, 90, 90, 16))
        self.irreThree.setObjectName("irreThree")
        self.irreFour = QtWidgets.QRadioButton(self.irreGroupBox)
        self.irreFour.setGeometry(QtCore.QRect(10, 120, 90, 16))
        self.irreFour.setObjectName("irreFour")
        self.irreFive = QtWidgets.QRadioButton(self.irreGroupBox)
        self.irreFive.setGeometry(QtCore.QRect(10, 150, 90, 16))
        self.irreFive.setObjectName("irreFive")
        self.irreFormatButton = QtWidgets.QPushButton(self.irrelevant)
        self.irreFormatButton.setGeometry(QtCore.QRect(930, 340, 75, 23))
        self.irreFormatButton.setObjectName("irreFormatButton")
        self.label = QtWidgets.QLabel(self.irrelevant)
        self.label.setGeometry(QtCore.QRect(280, 140, 471, 16))
        self.label.setObjectName("label")
        self.tabWidget.addTab(self.irrelevant, "")
        self.blank = QtWidgets.QWidget()
        self.blank.setObjectName("blank")
        self.blankAllocateButton = QtWidgets.QPushButton(self.blank)
        self.blankAllocateButton.setGeometry(QtCore.QRect(50, 40, 75, 23))
        self.blankAllocateButton.setObjectName("blankAllocateButton")
        self.blankText = QtWidgets.QTextEdit(self.blank)
        self.blankText.setGeometry(QtCore.QRect(220, 30, 481, 311))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.blankText.setFont(font)
        self.blankText.setObjectName("blankText")
        self.answerText = QtWidgets.QTextEdit(self.blank)
        self.answerText.setGeometry(QtCore.QRect(220, 360, 481, 61))
        self.answerText.setObjectName("answerText")
        self.blankAllocateLabel = QtWidgets.QLabel(self.blank)
        self.blankAllocateLabel.setGeometry(QtCore.QRect(20, 70, 191, 51))
        self.blankAllocateLabel.setObjectName("blankAllocateLabel")
        self.blankFormatAnswersButton = QtWidgets.QPushButton(self.blank)
        self.blankFormatAnswersButton.setGeometry(QtCore.QRect(40, 510, 121, 23))
        self.blankFormatAnswersButton.setObjectName("blankFormatAnswersButton")
        self.blankButton = QtWidgets.QPushButton(self.blank)
        self.blankButton.setGeometry(QtCore.QRect(50, 170, 75, 23))
        self.blankButton.setObjectName("blankButton")
        self.blankTextCopyButton = QtWidgets.QPushButton(self.blank)
        self.blankTextCopyButton.setGeometry(QtCore.QRect(790, 160, 75, 23))
        self.blankTextCopyButton.setObjectName("blankTextCopyButton")
        self.blankAnswersCopyButton = QtWidgets.QPushButton(self.blank)
        self.blankAnswersCopyButton.setGeometry(QtCore.QRect(860, 470, 101, 23))
        self.blankAnswersCopyButton.setObjectName("blankAnswersCopyButton")
        self.blankFormatAnswersLabel = QtWidgets.QLabel(self.blank)
        self.blankFormatAnswersLabel.setGeometry(QtCore.QRect(50, 540, 111, 20))
        self.blankFormatAnswersLabel.setObjectName("blankFormatAnswersLabel")
        self.answerTextLabel = QtWidgets.QLabel(self.blank)
        self.answerTextLabel.setGeometry(QtCore.QRect(730, 380, 56, 12))
        self.answerTextLabel.setObjectName("answerTextLabel")
        self.addToAnswerButon = QtWidgets.QPushButton(self.blank)
        self.addToAnswerButon.setGeometry(QtCore.QRect(50, 380, 121, 23))
        self.addToAnswerButon.setObjectName("addToAnswerButon")
        self.blankRemoveButton = QtWidgets.QPushButton(self.blank)
        self.blankRemoveButton.setGeometry(QtCore.QRect(80, 470, 75, 23))
        self.blankRemoveButton.setObjectName("blankRemoveButton")
        self.answerTableWidget = QtWidgets.QTableWidget(self.blank)
        self.answerTableWidget.setGeometry(QtCore.QRect(220, 440, 491, 171))
        self.answerTableWidget.setRowCount(0)
        self.answerTableWidget.setColumnCount(0)
        self.answerTableWidget.setObjectName("answerTableWidget")
        self.answerTableWidget.horizontalHeader().setStretchLastSection(True)
        self.tabWidget.addTab(self.blank, "")
        self.pronoun = QtWidgets.QWidget()
        self.pronoun.setObjectName("pronoun")
        self.proAllocateButton = QtWidgets.QPushButton(self.pronoun)
        self.proAllocateButton.setGeometry(QtCore.QRect(30, 50, 75, 23))
        self.proAllocateButton.setObjectName("proAllocateButton")
        self.proText = QtWidgets.QTextEdit(self.pronoun)
        self.proText.setGeometry(QtCore.QRect(260, 30, 681, 631))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.proText.setFont(font)
        self.proText.setObjectName("proText")
        self.sheButton = QtWidgets.QPushButton(self.pronoun)
        self.sheButton.setGeometry(QtCore.QRect(30, 130, 75, 23))
        self.sheButton.setObjectName("sheButton")
        self.youButton = QtWidgets.QPushButton(self.pronoun)
        self.youButton.setGeometry(QtCore.QRect(30, 180, 75, 23))
        self.youButton.setObjectName("youButton")
        self.proAllocateLabel = QtWidgets.QLabel(self.pronoun)
        self.proAllocateLabel.setGeometry(QtCore.QRect(20, 70, 191, 51))
        self.proAllocateLabel.setObjectName("proAllocateLabel")
        self.proCount = QtWidgets.QLabel(self.pronoun)
        self.proCount.setGeometry(QtCore.QRect(30, 260, 101, 16))
        self.proCount.setObjectName("proCount")
        self.proFormatButton = QtWidgets.QPushButton(self.pronoun)
        self.proFormatButton.setGeometry(QtCore.QRect(30, 290, 75, 23))
        self.proFormatButton.setObjectName("proFormatButton")
        self.proCopyTextButton = QtWidgets.QPushButton(self.pronoun)
        self.proCopyTextButton.setGeometry(QtCore.QRect(30, 410, 75, 23))
        self.proCopyTextButton.setObjectName("proCopyTextButton")
        self.tabWidget.addTab(self.pronoun, "")
        self.voca = QtWidgets.QWidget()
        self.voca.setObjectName("voca")
        self.vocaText = QtWidgets.QTextEdit(self.voca)
        self.vocaText.setGeometry(QtCore.QRect(240, 20, 681, 451))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(14)
        self.vocaText.setFont(font)
        self.vocaText.setObjectName("vocaText")
        self.vocaAllocateButton = QtWidgets.QPushButton(self.voca)
        self.vocaAllocateButton.setGeometry(QtCore.QRect(20, 40, 75, 23))
        self.vocaAllocateButton.setObjectName("vocaAllocateButton")
        self.vocaAllocateLabel = QtWidgets.QLabel(self.voca)
        self.vocaAllocateLabel.setGeometry(QtCore.QRect(10, 80, 191, 51))
        self.vocaAllocateLabel.setObjectName("vocaAllocateLabel")
        self.vocaRightButton = QtWidgets.QPushButton(self.voca)
        self.vocaRightButton.setGeometry(QtCore.QRect(740, 520, 81, 23))
        self.vocaRightButton.setObjectName("vocaRightButton")
        self.vocaLeftButton = QtWidgets.QPushButton(self.voca)
        self.vocaLeftButton.setGeometry(QtCore.QRect(390, 520, 75, 23))
        self.vocaLeftButton.setObjectName("vocaLeftButton")
        self.vocaFormatButton = QtWidgets.QPushButton(self.voca)
        self.vocaFormatButton.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.vocaFormatButton.setObjectName("vocaFormatButton")
        self.vocaCopyTextButton = QtWidgets.QPushButton(self.voca)
        self.vocaCopyTextButton.setGeometry(QtCore.QRect(20, 390, 75, 23))
        self.vocaCopyTextButton.setObjectName("vocaCopyTextButton")
        self.vocaStatusLabel = QtWidgets.QLabel(self.voca)
        self.vocaStatusLabel.setGeometry(QtCore.QRect(20, 350, 101, 16))
        self.vocaStatusLabel.setObjectName("vocaStatusLabel")
        self.vocaWordText = QtWidgets.QTextEdit(self.voca)
        self.vocaWordText.setGeometry(QtCore.QRect(490, 510, 231, 51))
        self.vocaWordText.setObjectName("vocaWordText")
        self.vocaNewWord = QtWidgets.QTextEdit(self.voca)
        self.vocaNewWord.setGeometry(QtCore.QRect(450, 570, 321, 51))
        self.vocaNewWord.setObjectName("vocaNewWord")
        self.vocaPos = QtWidgets.QLabel(self.voca)
        self.vocaPos.setGeometry(QtCore.QRect(670, 490, 56, 12))
        self.vocaPos.setObjectName("vocaPos")
        self.vocaTableWidget = QtWidgets.QTableWidget(self.voca)
        self.vocaTableWidget.setGeometry(QtCore.QRect(20, 500, 301, 151))
        self.vocaTableWidget.setRowCount(0)
        self.vocaTableWidget.setColumnCount(0)
        self.vocaTableWidget.setObjectName("vocaTableWidget")
        self.vocaTableWidget.horizontalHeader().setStretchLastSection(True)
        self.vocaRemoveButton = QtWidgets.QPushButton(self.voca)
        self.vocaRemoveButton.setGeometry(QtCore.QRect(20, 470, 75, 23))
        self.vocaRemoveButton.setObjectName("vocaRemoveButton")
        self.vocaAnswerText = QtWidgets.QTextEdit(self.voca)
        self.vocaAnswerText.setGeometry(QtCore.QRect(960, 250, 221, 221))
        self.vocaAnswerText.setObjectName("vocaAnswerText")
        self.vocaCopyAnswerButton = QtWidgets.QPushButton(self.voca)
        self.vocaCopyAnswerButton.setGeometry(QtCore.QRect(960, 490, 91, 23))
        self.vocaCopyAnswerButton.setObjectName("vocaCopyAnswerButton")
        self.vocaAnswerLabel = QtWidgets.QLabel(self.voca)
        self.vocaAnswerLabel.setGeometry(QtCore.QRect(1080, 490, 81, 16))
        self.vocaAnswerLabel.setObjectName("vocaAnswerLabel")
        self.tabWidget.addTab(self.voca, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1358, 21))
        self.menubar.setObjectName("menubar")
        self.menuword_under_mouse = QtWidgets.QMenu(self.menubar)
        self.menuword_under_mouse.setObjectName("menuword_under_mouse")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuword_under_mouse.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">My first morning in New York, I put on my girl-writer dress and heels and went to meet my editor, looking forward to a promising day. I figured we would start editing together that very morning, and then he could give me the last of the advance. It would turn out that I had bounced back from this devastating setback and that truth and beauty had once again triumphed. Everyone would be so shocked to hear that this book had almost been thrown away. But my hopes were shattered when my editor said, &quot;I\'m sorry.&quot; I looked at him quizzically. &quot;I am so, so sorry,&quot; he said. &quot;But it still doesn\'t work.&quot; I sat there staring at him as if his face were melting. I kept touching my forehead, the way you pat your head to make sure your hair is okay. Then I started to cry and told him I had to go right that very second. He told me to phone him the next day. I said I would, although I had no intention of actually doing so. </p></body></html>"))
        self.fireButton.setText(_translate("MainWindow", "fire"))
        self.highlightButton.setText(_translate("MainWindow", "highlight"))
        self.underlineButton.setText(_translate("MainWindow", "underline"))
        self.italicButton.setText(_translate("MainWindow", "italic"))
        self.boldButton.setText(_translate("MainWindow", "bold"))
        self.openFileButton.setText(_translate("MainWindow", "Open File"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.main), _translate("MainWindow", "main"))
        self.sentTokenizeButton.setText(_translate("MainWindow", "sent_tokenize"))
        self.totalSentLabel.setText(_translate("MainWindow", "문장 수:"))
        self.givenDownButton.setText(_translate("MainWindow", "DOWN"))
        self.givenLabel.setText(_translate("MainWindow", "given"))
        self.firstLabel.setText(_translate("MainWindow", "first"))
        self.secondLabel.setText(_translate("MainWindow", "second"))
        self.thirdLabel.setText(_translate("MainWindow", "third"))
        self.firstUpButton.setText(_translate("MainWindow", "UP"))
        self.secondUpButton.setText(_translate("MainWindow", "UP"))
        self.thirdUpButton.setText(_translate("MainWindow", "UP"))
        self.firstDownButton.setText(_translate("MainWindow", "DOWN"))
        self.secondDownButton.setText(_translate("MainWindow", "DOWN"))
        self.tokenRadioBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.optionTypeABCButtonOne.setText(_translate("MainWindow", "A C B"))
        self.optionTypeABCButtonTwo.setText(_translate("MainWindow", "B A C"))
        self.optionTypeABCButtonThree.setText(_translate("MainWindow", "B C A"))
        self.optionTypeABCButtonFour.setText(_translate("MainWindow", "C A B"))
        self.optionTypeABCButtonFive.setText(_translate("MainWindow", "C B A"))
        self.optionTypeABCRandomButton.setText(_translate("MainWindow", "random"))
        self.givenCopyButton.setText(_translate("MainWindow", "G"))
        self.firstCopyButton.setText(_translate("MainWindow", "A"))
        self.secondCopyButton.setText(_translate("MainWindow", "B"))
        self.thirdCopyButton.setText(_translate("MainWindow", "C"))
        self.tokenChoiceCopyButton.setText(_translate("MainWindow", "choices copy"))
        self.ABCCopyButton.setText(_translate("MainWindow", "ABC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.token), _translate("MainWindow", "token"))
        self.insertionAllocateButton.setText(_translate("MainWindow", "allocate"))
        self.insertionGivenCopyButton.setText(_translate("MainWindow", "copy given"))
        self.insertionTextCopyButton.setText(_translate("MainWindow", "copy text"))
        self.insertionGivenLabel.setText(_translate("MainWindow", "given"))
        self.insertionFullTextLabel.setText(_translate("MainWindow", "text"))
        self.groupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.insertionOne.setText(_translate("MainWindow", "①"))
        self.insertionTwo.setText(_translate("MainWindow", "②"))
        self.insertionThree.setText(_translate("MainWindow", "③"))
        self.insertionFour.setText(_translate("MainWindow", "④"))
        self.insertionFive.setText(_translate("MainWindow", "⑤"))
        self.insertionAllocateLabel.setText(_translate("MainWindow", "click button to allocate"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.insertion), _translate("MainWindow", "insertion"))
        self.irreAllocateButton.setText(_translate("MainWindow", "allocate"))
        self.irreAllocateLabel.setText(_translate("MainWindow", "click button to allocate"))
        self.irreTextCopyButton.setText(_translate("MainWindow", "copy text"))
        self.irreGivenLabel.setText(_translate("MainWindow", "IRRELEVANT"))
        self.irreFullTextLabel.setText(_translate("MainWindow", "text"))
        self.irreGivenCopyButton.setText(_translate("MainWindow", "copy given"))
        self.irreGroupBox.setTitle(_translate("MainWindow", "GroupBox"))
        self.irreOne.setText(_translate("MainWindow", "①"))
        self.irreTwo.setText(_translate("MainWindow", "②"))
        self.irreThree.setText(_translate("MainWindow", "③"))
        self.irreFour.setText(_translate("MainWindow", "④"))
        self.irreFive.setText(_translate("MainWindow", "⑤"))
        self.irreFormatButton.setText(_translate("MainWindow", "?format?"))
        self.label.setText(_translate("MainWindow", "****number is AFTER the sentence"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.irrelevant), _translate("MainWindow", "irrelevant"))
        self.blankAllocateButton.setText(_translate("MainWindow", "allocate"))
        self.blankAllocateLabel.setText(_translate("MainWindow", "click button to allocate"))
        self.blankFormatAnswersButton.setText(_translate("MainWindow", "format answers"))
        self.blankButton.setText(_translate("MainWindow", "blank it"))
        self.blankTextCopyButton.setText(_translate("MainWindow", "copy text"))
        self.blankAnswersCopyButton.setText(_translate("MainWindow", "copy answers"))
        self.blankFormatAnswersLabel.setText(_translate("MainWindow", "answer: "))
        self.answerTextLabel.setText(_translate("MainWindow", "length"))
        self.addToAnswerButon.setText(_translate("MainWindow", "add to answers"))
        self.blankRemoveButton.setText(_translate("MainWindow", "remove row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.blank), _translate("MainWindow", "blank"))
        self.proAllocateButton.setText(_translate("MainWindow", "allocate"))
        self.sheButton.setText(_translate("MainWindow", "he/she"))
        self.youButton.setText(_translate("MainWindow", "you / i"))
        self.proAllocateLabel.setText(_translate("MainWindow", "click button to allocate"))
        self.proCount.setText(_translate("MainWindow", "F5 to underline "))
        self.proFormatButton.setText(_translate("MainWindow", "format"))
        self.proCopyTextButton.setText(_translate("MainWindow", "copy text"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.pronoun), _translate("MainWindow", "pronoun"))
        self.vocaAllocateButton.setText(_translate("MainWindow", "allocate"))
        self.vocaAllocateLabel.setText(_translate("MainWindow", "click button to allocate"))
        self.vocaRightButton.setText(_translate("MainWindow", "NW on right"))
        self.vocaLeftButton.setText(_translate("MainWindow", "NW on left"))
        self.vocaFormatButton.setText(_translate("MainWindow", "format"))
        self.vocaCopyTextButton.setText(_translate("MainWindow", "copy text"))
        self.vocaStatusLabel.setText(_translate("MainWindow", "what to do"))
        self.vocaPos.setText(_translate("MainWindow", "position"))
        self.vocaTableWidget.setSortingEnabled(True)
        self.vocaRemoveButton.setText(_translate("MainWindow", "remove row"))
        self.vocaCopyAnswerButton.setText(_translate("MainWindow", "copy answer"))
        self.vocaAnswerLabel.setText(_translate("MainWindow", "answer is: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.voca), _translate("MainWindow", "voca"))
        self.menuword_under_mouse.setTitle(_translate("MainWindow", "word under mouse"))
