# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'textcursor.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 650)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.inputText = QtWidgets.QTextEdit(self.centralwidget)
        self.inputText.setGeometry(QtCore.QRect(10, 20, 561, 281))
        self.inputText.setObjectName("inputText")
        self.answerLine = QtWidgets.QLineEdit(self.centralwidget)
        self.answerLine.setGeometry(QtCore.QRect(90, 320, 201, 31))
        self.answerLine.setObjectName("answerLine")
        self.workButton = QtWidgets.QPushButton(self.centralwidget)
        self.workButton.setGeometry(QtCore.QRect(300, 320, 101, 23))
        self.workButton.setObjectName("workButton")
        self.workLabel = QtWidgets.QLabel(self.centralwidget)
        self.workLabel.setGeometry(QtCore.QRect(600, 90, 56, 31))
        self.workLabel.setObjectName("workLabel")
        self.jjaButton = QtWidgets.QPushButton(self.centralwidget)
        self.jjaButton.setGeometry(QtCore.QRect(1000, 30, 75, 23))
        self.jjaButton.setObjectName("jjaButton")
        self.jjbButton = QtWidgets.QPushButton(self.centralwidget)
        self.jjbButton.setGeometry(QtCore.QRect(1000, 60, 75, 23))
        self.jjbButton.setObjectName("jjbButton")
        self.synButton = QtWidgets.QPushButton(self.centralwidget)
        self.synButton.setGeometry(QtCore.QRect(1000, 90, 75, 23))
        self.synButton.setObjectName("synButton")
        self.trgButton = QtWidgets.QPushButton(self.centralwidget)
        self.trgButton.setGeometry(QtCore.QRect(1000, 120, 75, 23))
        self.trgButton.setObjectName("trgButton")
        self.antButton = QtWidgets.QPushButton(self.centralwidget)
        self.antButton.setGeometry(QtCore.QRect(1000, 150, 75, 23))
        self.antButton.setObjectName("antButton")
        self.spcButton = QtWidgets.QPushButton(self.centralwidget)
        self.spcButton.setGeometry(QtCore.QRect(1000, 180, 75, 23))
        self.spcButton.setObjectName("spcButton")
        self.genButton = QtWidgets.QPushButton(self.centralwidget)
        self.genButton.setGeometry(QtCore.QRect(1000, 210, 75, 23))
        self.genButton.setObjectName("genButton")
        self.comButton = QtWidgets.QPushButton(self.centralwidget)
        self.comButton.setGeometry(QtCore.QRect(1000, 240, 75, 23))
        self.comButton.setObjectName("comButton")
        self.parButton = QtWidgets.QPushButton(self.centralwidget)
        self.parButton.setGeometry(QtCore.QRect(1000, 270, 75, 23))
        self.parButton.setObjectName("parButton")
        self.bgaButton = QtWidgets.QPushButton(self.centralwidget)
        self.bgaButton.setGeometry(QtCore.QRect(1000, 300, 75, 23))
        self.bgaButton.setObjectName("bgaButton")
        self.bgbButton = QtWidgets.QPushButton(self.centralwidget)
        self.bgbButton.setGeometry(QtCore.QRect(1000, 330, 75, 23))
        self.bgbButton.setObjectName("bgbButton")
        self.jjaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.jjaLineEdit.setGeometry(QtCore.QRect(732, 30, 251, 20))
        self.jjaLineEdit.setObjectName("jjaLineEdit")
        self.jjbLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.jjbLineEdit.setGeometry(QtCore.QRect(732, 60, 251, 20))
        self.jjbLineEdit.setObjectName("jjbLineEdit")
        self.synLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.synLineEdit.setGeometry(QtCore.QRect(730, 90, 251, 20))
        self.synLineEdit.setObjectName("synLineEdit")
        self.trgLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.trgLineEdit.setGeometry(QtCore.QRect(730, 120, 251, 20))
        self.trgLineEdit.setObjectName("trgLineEdit")
        self.antLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.antLineEdit.setGeometry(QtCore.QRect(730, 150, 251, 20))
        self.antLineEdit.setObjectName("antLineEdit")
        self.spcLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.spcLineEdit.setGeometry(QtCore.QRect(730, 180, 251, 20))
        self.spcLineEdit.setObjectName("spcLineEdit")
        self.genLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.genLineEdit.setGeometry(QtCore.QRect(730, 210, 251, 20))
        self.genLineEdit.setObjectName("genLineEdit")
        self.comLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.comLineEdit.setGeometry(QtCore.QRect(730, 240, 251, 20))
        self.comLineEdit.setObjectName("comLineEdit")
        self.parLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.parLineEdit.setGeometry(QtCore.QRect(730, 270, 251, 20))
        self.parLineEdit.setObjectName("parLineEdit")
        self.bgaLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.bgaLineEdit.setGeometry(QtCore.QRect(730, 300, 251, 20))
        self.bgaLineEdit.setObjectName("bgaLineEdit")
        self.bgbLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.bgbLineEdit.setGeometry(QtCore.QRect(730, 330, 251, 20))
        self.bgbLineEdit.setObjectName("bgbLineEdit")
        self.fullListWidget = QtWidgets.QListWidget(self.centralwidget)
        self.fullListWidget.setGeometry(QtCore.QRect(20, 450, 511, 81))
        self.fullListWidget.setObjectName("fullListWidget")
        self.fullTableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.fullTableWidget.setGeometry(QtCore.QRect(650, 370, 361, 231))
        self.fullTableWidget.setObjectName("fullTableWidget")
        self.fullTableWidget.setColumnCount(0)
        self.fullTableWidget.setRowCount(0)
        self.toSimpleButton = QtWidgets.QPushButton(self.centralwidget)
        self.toSimpleButton.setGeometry(QtCore.QRect(300, 370, 91, 51))
        self.toSimpleButton.setObjectName("toSimpleButton")
        self.nounSimpleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.nounSimpleLineEdit.setGeometry(QtCore.QRect(90, 360, 201, 31))
        self.nounSimpleLineEdit.setObjectName("nounSimpleLineEdit")
        self.verbSimpleLineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.verbSimpleLineEdit.setGeometry(QtCore.QRect(90, 400, 201, 31))
        self.verbSimpleLineEdit.setObjectName("verbSimpleLineEdit")
        self.nounSimpleLabel = QtWidgets.QLabel(self.centralwidget)
        self.nounSimpleLabel.setGeometry(QtCore.QRect(10, 370, 81, 16))
        self.nounSimpleLabel.setObjectName("nounSimpleLabel")
        self.verbSimpleLabel = QtWidgets.QLabel(self.centralwidget)
        self.verbSimpleLabel.setGeometry(QtCore.QRect(10, 410, 81, 16))
        self.verbSimpleLabel.setObjectName("verbSimpleLabel")
        self.openFileButton = QtWidgets.QPushButton(self.centralwidget)
        self.openFileButton.setGeometry(QtCore.QRect(530, 320, 75, 23))
        self.openFileButton.setObjectName("openFileButton")
        self.allWordsButton = QtWidgets.QPushButton(self.centralwidget)
        self.allWordsButton.setGeometry(QtCore.QRect(430, 320, 75, 23))
        self.allWordsButton.setObjectName("allWordsButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(580, 280, 101, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1115, 21))
        self.menubar.setObjectName("menubar")
        self.menuword_under_mouse = QtWidgets.QMenu(self.menubar)
        self.menuword_under_mouse.setObjectName("menuword_under_mouse")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuword_under_mouse.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.inputText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Gulim\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Biological organisms, including human societies both with and without market systems, discount distant outputs over those available at the present time based on risks associated with an uncertain future. As the timing of inputs and outputs varies greatly depending on the type of energy, there is a strong case to incorporate time when assessing energy alternatives. For example, the energy output from solar panels or wind power engines, where most investment happens before they begin producing, may need to be assessed differently when compared to most fossil fuel extraction technologies, where a large proportion of the energy output comes much sooner, and a larger (relative) proportion of inputs is applied during the extraction process, and not upfront. Thus fossil fuels, particularly oil and natural gas, in addition to having energy quality advantages (cost, storability, transportability, etc.) over many renewable technologies, also have a “temporal advantage” after accounting for human behavioral preference for current consumption/return.</p></body></html>"))
        self.workButton.setText(_translate("MainWindow", "work"))
        self.workLabel.setText(_translate("MainWindow", "TextLabel"))
        self.jjaButton.setText(_translate("MainWindow", "jja"))
        self.jjbButton.setText(_translate("MainWindow", "jjb"))
        self.synButton.setText(_translate("MainWindow", "syn"))
        self.trgButton.setText(_translate("MainWindow", "trg"))
        self.antButton.setText(_translate("MainWindow", "ant"))
        self.spcButton.setText(_translate("MainWindow", "spc"))
        self.genButton.setText(_translate("MainWindow", "gen"))
        self.comButton.setText(_translate("MainWindow", "com"))
        self.parButton.setText(_translate("MainWindow", "par"))
        self.bgaButton.setText(_translate("MainWindow", "bga"))
        self.bgbButton.setText(_translate("MainWindow", "bgb"))
        self.toSimpleButton.setText(_translate("MainWindow", "-> simple"))
        self.nounSimpleLabel.setText(_translate("MainWindow", "noun(simple)"))
        self.verbSimpleLabel.setText(_translate("MainWindow", "verb(simple)"))
        self.openFileButton.setText(_translate("MainWindow", "Open File"))
        self.allWordsButton.setText(_translate("MainWindow", "all words"))
        self.menuword_under_mouse.setTitle(_translate("MainWindow", "word under mouse"))
